### ISSUE TITLE
Check if address already has a tx in it or make a better path managment

### ISSUE THREAD

**Issue by johnnyasantoss** [librepay/LibrePay#5]
Imported from: https://gitlab.com/bitcoin-pos/app/issues/26

_When refreshing xpub the app resets the path for generating hd wallets, then it will generate address that have been previously used_

---

**Comment by edsonbrusque** [comment]
The app will not use xpubs anymore (because we're changing it to use OpenNode services) so this issue is obsolete and can be closed.
